build:
    environment:
        php:
            version: 7.0.8
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'php-clover'
checks:
    php: true
    javascript: true

filter:
    excluded_paths:
        - 'tests/*'
        - '*.min.js'
        - '*/vendor/*'
        - '*/dist/*'
        - 'bootstrap/*'
        - 'config/*'
        - 'modules/*'
        - 'plugins/anandpatel/*'
        - 'plugins/rainlab/*'
        - 'plugins/vojtasvoboda/*'
